apiVersion: apps/v1
kind: Deployment
metadata:
  name: timatech-www
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: timatech-www
  template:
    metadata:
      labels:
        app: timatech-www
    spec:
      containers:
      - image: nicktimakondu/timatech:latest
        name: timattech-www
        ports:
        - containerPort: 8080
