apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "timatech.name" . }}-backend-config
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
    port: 8080