apiVersion: v1
kind: Service
metadata:
  name: {{ include "timatech.name" . }}-www
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"ports": {"http":"{{ include "timatech.name" . }}-backend-config"}}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {{ include "timatech.name" . }}-www
  
